name: Bug Report
description: Report an issue you are experiencing with the Trainworks & Couplers mod.
title: "[BR] "
labels: ["CAT: Bug Report", "ATN: Needs Attention"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to improve Trainworks & Couplers!
- type: textarea
  id: description
  attributes:
    label: "Bug Description"
    description: "Please describe the issue in as much detail as possible."
  validations:
    required: true
- type: textarea
  id: additional
  attributes:
    label: "Additional Info"
    description: "More information allows us to investigate the issue faster."
    placeholder: "N/A"
  validations:
    required: false
- type: checkboxes
  id: requirements
  attributes:
    label: "Issue Requirements"
    description: "Failure to do these things may result in the removal of your issue."
    options:
    - label: "Your title is professional."
      required: true
    - label: "Your title is properly capitalized."
      required: true
    - label: "Your post uses full sentences, proper grammar, and punctuation."
      required: true
  validations:
    required: true