require("prototypes.item")
require("prototypes.sound")
require("prototypes.couplers")
require("prototypes.sensors")
require("prototypes.input")
require("prototypes.signals")
require("prototypes.recipe")
require("prototypes.tips-and-tricks")