require("prototypes.item")
require("prototypes.entity.sounds")
require("prototypes.entity.entities")
require("prototypes.inputs")
require("prototypes.signal")
require("prototypes.recipe")
require("prototypes.tips-and-tricks")